name: Docker Image â€” Staging

on:
  push:
    tags:
      - "v*-dev.*"

jobs:
  docker:
    uses: freddyandreszambrano/Platform-CI/.github/workflows/django-docker-image.yml@v1.0.1
    with:
      docker_image: ${{ vars.DOCKER_IMAGE }}
      dockerfile: Dockerfile
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}